// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiwqfbwnfkhmwvznwvlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpd3FmYnduZmtobXd2em53dmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Njc5NjEsImV4cCI6MjA1OTU0Mzk2MX0.P3Om1c8cNRKtJDfR5Ylg_qfQaEy2nLg98iRhaFvjeGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);